

CREATE SEQUENCE SEQ_'테이블명' INCREMENT BY '증가값' START WITH '초기값';



CREATE SEQUENCE SEQ_BOARD INCREMENT BY 1 START WITH 1;


INSERT INTO MANAGERS VALUES (1, 'HONGS', '홍길동', 'hhh1234@naver.com', '1234', '111-1111-1111', '2024-01-01', '123456-1234567');
INSERT INTO MANAGERS VALUES (2, 'KIM', '김길동', 'KKK5678@naver.com', '5678', '222-2222-2222', '2023-01-23', '345678-3456789');
INSERT INTO MANAGERS VALUES (3, 'PARK', '박길동', 'bbb2901@naver.com', '12345', '333-3333-3333', '2022-02-13', '654321-1235567');


INSERT INTO board VALUES (SEQ_BOARD.NEXTVAL, '가장 좋아하는 여자 연예인', 1, '2024-03-01', '2024-03-15', 1);

INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES (SEQ_BOARD.CURRVAL, 1, '박보영' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES (SEQ_BOARD.CURRVAL, 2, '한소희' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES (SEQ_BOARD.CURRVAL, 3, '홍수주' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES (SEQ_BOARD.CURRVAL, 4, '권나라' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES (SEQ_BOARD.CURRVAL, 5, '조보아' ) ;

INSERT INTO board VALUES (SEQ_BOARD.NEXTVAL, '선호하는 반려동물', 1, '2024-03-10', '2024-03-20', 2);

INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 1, '강아지' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 2, '고양이' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 3, '거북이' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 4, '토끼' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 5, '물개' ) ;

INSERT INTO board VALUES (SEQ_BOARD.NEXTVAL, '요즘 정주행하고 있는 드라마는 ?', 1, '2024-03-05', '2024-03-15', 1);

INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 1, '웨딩 임파서블' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 2, '살인장난감' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 3, '로얄로더' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 4, '끝내주는 해결사' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 5, '피라미드 게임' ) ;

INSERT INTO board VALUES (SEQ_BOARD.NEXTVAL, '최근 본 영화 중 추천하고 싶은 영화는 ?', 1, '2024-03-05', '2024-03-15', 3);

INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 1, '듄: 파트2' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 2, '파묘' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 3, '윙카' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 4, '귀멸의 칼날' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 5, '소풍' ) ;

INSERT INTO board VALUES (SEQ_BOARD.NEXTVAL, '개봉 예정 영화 중 기대되는 영화는 ?', 1, '2024-03-05', '2024-03-15', 3);

INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 1, '브레드 이발소' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 2, '아이엠 티라노' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 3, '패스트 라이브즈' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 4, '가여운 것들' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 5, '비트' ) ;


INSERT INTO board VALUES (SEQ_BOARD.NEXTVAL, '집들이 선물로 받고싶은 선물은 ?', 1, '2024-03-01', '2024-03-07', 2);

INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 1, '휴지' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 2, '세제' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 3, '무드등' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 4, '수건세트' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 5, '찻잔/커피잔 세트' ) ;


INSERT INTO board VALUES (SEQ_BOARD.NEXTVAL, '배스킨라빈스 맛 종류 중 선호하는 맛은?', 1, '2024-02-01', '2024-03-07', 2);
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 1, '엄마는외계인' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 2, '사랑에빠진딸기' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 3, '초코나무숲' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 4, '아몬드봉봉' ) ;
INSERT INTO CATEGORY( BOARD_NUMBER, CATEGORY_NUMBER, CATEGORY_CONTENT) VALUES ( SEQ_BOARD.CURRVAL, 5, '황치즈드래곤볼' ) ;

ROLLBACK;

INSERT INTO member_info
values('1','dog123','카리나','dogh123@naver.com','ss1234','940130-1335794','19-01-20','010-1234-5698','경기도 수원시');
INSERT INTO member_info
values('2','cat123','윈터','cat123@naver.com','sf1234','920321-1134873','20-04-10','010-5479-5468','경기도  광교시');

INSERT INTO member_info
values('3','gifaffe123','닝닝','gifaffe123@naver.com','se1234','780824-1478526','13-04-30','010-4564-4567','경기도 오산시');

INSERT INTO member_info
values('4','lion123','지젤','lion123@naver.com','sq1234','660201-1574125','10-08-30','010-7895-3454','경기도 화성시');

INSERT INTO member_info
values('5','rabbit123','오혜원','rabbit123@naver.com','st1234','850421-1359841','17-02-27','010-7891-7893','서울특별시 강남구');

INSERT INTO member_info
values('6','tiger123','설윤','tiger123@naver.com','sj1234','870812-2045631','08-04-30','010-7894-3456','충청북도 대전광역시');

INSERT INTO member_info
values('7','elephant123','릴리','elephant123','sl1234','730530-3458647','05-02-12','010-2134-7891','충청남도 천안시');

INSERT INTO member_info
values('8','lizard123','안유진','lizard123@naver.com','os1234','660512-2015486','12-01-12','010-6457-2314','충청남도 아산시');

INSERT INTO member_info
values('9','fire123','장원영','fire123@naver.com','sp1234','870122-2178963','22-04-30','010-3457-4567','전북특별자치도 전주시');

INSERT INTO member_info
values('10','cool123','김채원','cool123@naver.com','sb1234','840103-2766841','18-01-20','010-1234-9123','전북특별자치도 익산시');
COMMIT;

INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(1, 1, 1);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(2, 1, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(3, 1, 3);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(4, 1, 1);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(5, 1, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(6, 1, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(7, 1, 3);


-- 1번 게시판 투표
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(1, 1, 1);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(2, 1, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(3, 1, 3);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(4, 1, 1);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(5, 1, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(6, 1, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(7, 1, 3);

-- 2번 게시판 투표
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(1, 2, 5);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(2, 2, 5);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(3, 2, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(4, 2, 3);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(5, 2, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(6, 2, 1);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(7, 2, 1);

-- 3번 게시판 투표
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(1, 3, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(2, 3, 3);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(3, 3, 3);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(4, 3, 3);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(5, 3, 3);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(6, 3, 5);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(7, 3, 5);

-- 4번 게시판 투표
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(1, 4, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(2, 4, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(3, 4, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(4, 4, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(5, 4, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(6, 4, 1);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(7, 4, 4);

-- 5번 게시판 투표
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(1, 5, 1);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(2, 5, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(3, 5, 3);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(4, 5, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(5, 5, 5);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(6, 5, 1);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(7, 5, 1);

-- 6번 게시판 투표
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(1, 6, 3);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(2, 6, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(3, 6, 5);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(4, 6, 5);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(5, 6, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(6, 6, 3);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(7, 6, 3);

-- 7번 게시판 투표
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(1, 7, 1);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(2, 7, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(3, 7, 3);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(4, 7, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(5, 7, 5);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(6, 7, 5);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(7, 7, 5);

-- 8번 게시판 투표
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(1, 8, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(2, 8, 1);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(3, 8, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(4, 8, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(5, 8, 2);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(6, 8, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(7, 8, 5);

-- 9번 게시판 투표
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(1, 9, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(2, 9, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(3, 9, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(4, 9, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(5, 9, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(6, 9, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(7, 9, 4);

-- 10번 게시판 투표
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(1, 10, 3);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(2, 10, 1);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(3, 10, 1);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(4, 10, 1);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(5, 10, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(6, 10, 4);
INSERT INTO vote (MEMBER_NUMBER, BOARD_NUMBER, CATEGORY_NUMBER) VALUES(7, 10, 5);

SELECT *
FROM board;
SELECT *
FROM category;
SELECT *
FROM vote;

--ALTER TABLE board RENAME COLUMN END_DATE1 TO END_DATE;
--ALTER TABLE board RENAME COLUMN END_DATE TO START_DATE;

ALTER TABLE category ADD VOTE_PERCENT VARCHAR(100);

COMMIT;
-- 날짜 바꾸기
UPDATE board
SET start_date = '24-04-01',
    end_date = '24-04-10'
WHERE board_number = 3;

UPDATE board
SET board_title = '가장 싫어하는 여자 연예인'
WHERE board_number = 1;

SELECT *
FROM board b JOIN category c ON b.board_number = c.board_number
WHERE b.board_number = 3;

UPDATE category
SET vote_percent = 
(SELECT BOARD_NUMBER, CATEGORY_NUMBER, COUNT(*)
FROM vote
GROUP BY BOARD_NUMBER, CATEGORY_NUMBER);

CREATE OR REPLACE VIEW vote_percent
AS (
SELECT category_number
    , vote
    , total_vote
    , RPAD(' ', vote + 1, '▒') || '  ' || ROUND(vote/total_vote * 100,2) || '%' vote_bar
FROM(
    SELECT category_number 
        , COUNT(category_number) vote
        , (SELECT COUNT(*) FROM vote) total_vote
    FROM vote
    GROUP BY category_number
    ORDER BY category_number
    )
    );

SELECT*
FROM vote_percent;

SELECT *
FROM category;

SELECT DISTINCT category_content, v.category_number, vote, vote_bar 
FROM vote_percent v , category c
WHERE v.category_number = v.category_number AND board_number = 1;


SELECT DISTINCT b.board_title, b.start_date, b.end_date
,CASE
    WHEN ROUND(SYSDATE - b.start_date) >= 0 AND ROUND(b.end_date - SYSDATE) <=0 THEN 1
    ELSE 0
END status
,m.managers_name
v.vote_percent, v.category_number
FROM board b JOIN managers m ON b.managers_number = m.managers_number
             CROSS JOIN vote_percent v
WHERE b.board_number = 1;

SELECT board_number, board_title,  DECODE(SURVEY_STATUS, 1, 0)
FROM board
WHERE board_number = ANY (
SELECT board_number
FROM board
WHERE END_DATE <= TRUNC(SYSDATE) OR START_DATE >= TRUNC(SYSDATE));

-- 투표 그래프 뷰 테이블 생성
CREATE OR REPLACE VIEW vote_percent
AS
(
    SELECT board_number
        , category_number
        , vote
        , RPAD(' ', ROUND(vote/total_vote*10) + 1, '▒') || '  ' || ROUND(vote/total_vote * 100, 2) || '%' vote_graph
        , ROUND(vote/total_vote * 100, 2) || '%'vote_percent 
    FROM(
        SELECT board_number 
            , category_number 
            , COUNT(board_number) vote
            , (SELECT COUNT(*) FROM vote p WHERE board_number = (SELECT COUNT(*)
                                                             FROM vote c
                                                             WHERE p.board_number = c.board_number))  total_vote

        FROM vote
        GROUP BY category_number, board_number
        ORDER BY board_number
        )
)ORDER BY board_number, category_number;

SELECT * FROM board;
SELECT * FROM vote_percent;
SELECT * FROM managers;

--필요한거 
--board : board_title, start_date, end_date -> status(상태) 항목수  
--managers : managers_name
--vote_percent


-- TODO : 상세 조회 뷰 테이블 생성
SELECT DISTINCT b.board_number, b.board_title, b.start_date, b.end_date
,CASE
    WHEN ROUND(SYSDATE - b.start_date) >= 0 AND ROUND(b.end_date - SYSDATE) <= 0 THEN 0
    WHEN ROUND(SYSDATE - b.start_date) >= 0 AND ROUND(b.end_date - SYSDATE) >= 0 THEN 1
    ELSE 2
END status
,m.managers_name
,v.vote_graph, v.category_number, v.vote_percent
FROM board b JOIN managers m ON b.managers_number = m.managers_number
             CROSS JOIN vote_percent v
ORDER BY b.board_number;